dist: trusty
sudo: required
language:
  - cpp
compiler:
  - g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - libglu1-mesa-dev
      - freeglut3
      - freeglut3-dev
      - mesa-common-dev
      - libglew-dev
      - libglfw3
      - libglfw3-dev
script:
#   - ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - g++ -v && make --version
  - make clean
  - make
